In [140]:
import pandas as pd
import json
import re
from pandas.io.json import json_normalize
import warnings
warnings.filterwarnings('ignore')

In [172]:
raw = pd.read_json(r'-coinbase_tweets.json', lines = True)
raw = raw[raw['lang']=='en']
print('shape: ', raw.shape)
raw.head(5)

shape:  (41772, 28)

,_type,url,date,content,renderedContent,id,user,replyCount,retweetCount,likeCount,...,media,retweetedTweet,quotedTweet,inReplyToTweetId,inReplyToUser,mentionedUsers,coordinates,place,hashtags,cashtags
0,snscrape.modules.twitter.Tweet,https://twitter.com/eyewareness/status/1587975...,2022-11-03 01:09:04+00:00,Shill me your best #crypto low cap alts on #Co...,Shill me your best #crypto low cap alts on #Co...,1587975112178933766,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,...,None,NaN,None,NaN,None,None,None,None,"[crypto, Coinbase]",None
1,snscrape.modules.twitter.Tweet,https://twitter.com/faryarshirzad/status/15879...,2022-11-03 01:07:53+00:00,Enormous thanks to @DrLisaCameronMP for hostin...,Enormous thanks to @DrLisaCameronMP for hostin...,1587974812466569216,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,...,None,NaN,None,1.587975e+18,"{'_type': 'snscrape.modules.twitter.User', 'us...","[{'_type': 'snscrape.modules.twitter.User', 'u...",None,None,None,None
2,snscrape.modules.twitter.Tweet,https://twitter.com/faryarshirzad/status/15879...,2022-11-03 01:07:52+00:00,The UK is @coinbase's largest market ex-US and...,The UK is @coinbase's largest market ex-US and...,1587974810931535874,"{'_type': 'snscrape.modules.twitter.User', 'us...",1,0,0,...,None,NaN,None,1.587975e+18,"{'_type': 'snscrape.modules.twitter.User', 'us...","[{'_type': 'snscrape.modules.twitter.User', 'u...",None,None,None,None
3,snscrape.modules.twitter.Tweet,https://twitter.com/faryarshirzad/status/15879...,2022-11-03 01:07:51+00:00,Today I shared @coinbase's thoughts on the UK’...,Today I shared @coinbase's thoughts on the UK’...,1587974806984708096,"{'_type': 'snscrape.modules.twitter.User', 'us...",1,0,2,...,"[{'_type': 'snscrape.modules.twitter.Photo', '...",NaN,None,NaN,None,"[{'_type': 'snscrape.modules.twitter.User', 'u...",None,None,None,None
5,snscrape.modules.twitter.Tweet,https://twitter.com/MamieMoses13/status/158797...,2022-11-03 01:07:24+00:00,Here's the current standings for #unMineable's...,Here's the current standings for #unMineable's...,1587974694275366912,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,...,"[{'_type': 'snscrape.modules.twitter.Photo', '...",NaN,None,NaN,None,None,None,None,"[unMineable, Coinbase, LTC]",None

In [173]:
# dropping unwanted columns
user = json_normalize(raw['user'])
user.drop(['linkTcourl', '_type', 'rawDescription', 'descriptionUrls','linkUrl', 'profileImageUrl', 'label',
           'profileBannerUrl', 'location','mediaCount', 'statusesCount', 'displayname',
           'listedCount', 'protected','description', 'label._type', 'label.description', 'label.url', 'label.badgeUrl', 'label.longDescription'], axis=1, inplace=True)
# rename if need # users.rename(columns={'_old_':'_new_', 'url':'profileUrl'}, inplace=True)
user.head(5)
#user.shape
##### delete things til content comes back

,username,id,verified,created,followersCount,friendsCount,favouritesCount,url
0,eyewareness,826977331042463745,False,2017-02-02T02:15:35+00:00,127,588,526,https://twitter.com/eyewareness
1,faryarshirzad,359126146,False,2011-08-21T02:17:55+00:00,4382,947,1062,https://twitter.com/faryarshirzad
2,faryarshirzad,359126146,False,2011-08-21T02:17:55+00:00,4382,947,1062,https://twitter.com/faryarshirzad
3,faryarshirzad,359126146,False,2011-08-21T02:17:55+00:00,4382,947,1062,https://twitter.com/faryarshirzad
4,MamieMoses13,1555658644548714497,False,2022-08-05T20:55:11+00:00,44,112,1,https://twitter.com/MamieMoses13

In [174]:
#users['created'] = users['DateTypeCol'].dt.strftime('%m/%d/%Y, hh:mm')

In [175]:
useri = pd.DataFrame(users)
useri.drop_duplicates(subset=['id'], inplace=True)
print("Shape: ", useri.shape)
useri.head(5)

Shape:  (18416, 8)

,username,id,verified,created,followersCount,friendsCount,favouritesCount,url
0,ALaksha_,1553705950007410689,False,2022-07-31T11:36:22+00:00,37,377,289,https://twitter.com/ALaksha_
1,Kaylee_Rao,1532283760284012544,False,2022-06-02T08:51:47+00:00,30,444,392,https://twitter.com/Kaylee_Rao
2,__Block_Chain,1534544839307628544,False,2022-06-08T14:36:34+00:00,14,11,125,https://twitter.com/__Block_Chain
3,Sonihitlor,1541777369408499712,False,2022-06-28T13:36:29+00:00,41,316,299,https://twitter.com/Sonihitlor
4,LION7931,1500048587341774851,False,2022-03-05T10:00:41+00:00,168,4616,1067,https://twitter.com/LION7931

In [176]:
# Transform 'raw_tweets' DataFrame

# Add column for 'userId'
user_id = []
for user in raw['user']:
    uid = user['id']
    user_id.append(uid)
raw['userId'] = user_id

# Remove less important columns if needed
cols = ['url', 'date', 'renderedContent', 'id', 'userId', 'replyCount', 'retweetCount', 'likeCount']
tweet_content = raw[cols]
tweet_content.rename(columns={'id':'tweetId', 'url':'tweetUrl'}, inplace=True)
tweet_content.head(5)

,tweetUrl,date,renderedContent,tweetId,userId,replyCount,retweetCount,likeCount
0,https://twitter.com/eyewareness/status/1587975...,2022-11-03 01:09:04+00:00,Shill me your best #crypto low cap alts on #Co...,1587975112178933766,826977331042463745,0,0,0
1,https://twitter.com/faryarshirzad/status/15879...,2022-11-03 01:07:53+00:00,Enormous thanks to @DrLisaCameronMP for hostin...,1587974812466569216,359126146,0,0,0
2,https://twitter.com/faryarshirzad/status/15879...,2022-11-03 01:07:52+00:00,The UK is @coinbase's largest market ex-US and...,1587974810931535874,359126146,1,0,0
3,https://twitter.com/faryarshirzad/status/15879...,2022-11-03 01:07:51+00:00,Today I shared @coinbase's thoughts on the UK’...,1587974806984708096,359126146,1,0,2
5,https://twitter.com/MamieMoses13/status/158797...,2022-11-03 01:07:24+00:00,Here's the current standings for #unMineable's...,1587974694275366912,1555658644548714497,0,0,0

In [177]:
# Convert to DataFrame, remove duplicates and keep only English tweets

tweets_content = pd.DataFrame(tweet_content)
tweets_content.drop_duplicates(subset=['tweetId'], inplace=True)
print("Shape: ", tweets_content.shape)
tweets_content.head(5)

Shape:  (41772, 8)

,tweetUrl,date,renderedContent,tweetId,userId,replyCount,retweetCount,likeCount
0,https://twitter.com/eyewareness/status/1587975...,2022-11-03 01:09:04+00:00,Shill me your best #crypto low cap alts on #Co...,1587975112178933766,826977331042463745,0,0,0
1,https://twitter.com/faryarshirzad/status/15879...,2022-11-03 01:07:53+00:00,Enormous thanks to @DrLisaCameronMP for hostin...,1587974812466569216,359126146,0,0,0
2,https://twitter.com/faryarshirzad/status/15879...,2022-11-03 01:07:52+00:00,The UK is @coinbase's largest market ex-US and...,1587974810931535874,359126146,1,0,0
3,https://twitter.com/faryarshirzad/status/15879...,2022-11-03 01:07:51+00:00,Today I shared @coinbase's thoughts on the UK’...,1587974806984708096,359126146,1,0,2
5,https://twitter.com/MamieMoses13/status/158797...,2022-11-03 01:07:24+00:00,Here's the current standings for #unMineable's...,1587974694275366912,1555658644548714497,0,0,0

In [179]:
tweets_content = pd.DataFrame(tweets_content)
tweets_content.drop_duplicates(subset=['tweetId'], inplace=True)
print("Shape: ", tweets_content.shape)
tweets_content.head(5)

Shape:  (41772, 8)

,tweetUrl,date,renderedContent,tweetId,userId,replyCount,retweetCount,likeCount
0,https://twitter.com/eyewareness/status/1587975...,2022-11-03 01:09:04+00:00,Shill me your best #crypto low cap alts on #Co...,1587975112178933766,826977331042463745,0,0,0
1,https://twitter.com/faryarshirzad/status/15879...,2022-11-03 01:07:53+00:00,Enormous thanks to @DrLisaCameronMP for hostin...,1587974812466569216,359126146,0,0,0
2,https://twitter.com/faryarshirzad/status/15879...,2022-11-03 01:07:52+00:00,The UK is @coinbase's largest market ex-US and...,1587974810931535874,359126146,1,0,0
3,https://twitter.com/faryarshirzad/status/15879...,2022-11-03 01:07:51+00:00,Today I shared @coinbase's thoughts on the UK’...,1587974806984708096,359126146,1,0,2
5,https://twitter.com/MamieMoses13/status/158797...,2022-11-03 01:07:24+00:00,Here's the current standings for #unMineable's...,1587974694275366912,1555658644548714497,0,0,0

In [180]:
tweets_content.drop_duplicates(inplace = True, subset = 'renderedContent')
tweets_content.shape

(38210, 8)

In [181]:
tweets_content.to_csv('coinbase_tweets.csv')

In [185]:
# merging csv files into one file

# import pandas as pd

# twit_stack = pd.concat(['blockchain_tweets.csv', 'btc_mining-tweets.csv', 'coinbase_tweets.csv', 'HODL_bitcoin_btc-tweets.csv', 
                        'moon_bit_btc_tweets.csv', 'nvda-stock-tweets.csv', 'nvda-tweets.csv', 'to_the_moon_tweets.csv'], axis=0)
# the_merge = twit_stack.to_csv('merge.csv', encoding='utf-8')

TypeError: cannot concatenate object of type '<class 'str'>'; only Series and DataFrame objs are valid